### ISSUE TITLE
may be there is some error.

### ISSUE THREAD

**Issue by Harry040** [weixsong/min-char-rnn#1]
wow, awesome project, thanks for sharing. But, I think the 10 formulation and 22 formulation are not correct .  There is some one to explain it?Thanks.

**Comment by weixsong** [comment]
Hi, @hongguangguo , could you provide a litter more of your concerns? or how you think about it, that we could discuss with it.

**Comment by Harry040** [comment]
I think the tenth formulation should be u' = w_hy \* h, not w_hh. it's the same as the fifth formulation.

**Comment by weixsong** [comment]
Yes, you are right. Thanks for pointing out this mistake.

**Comment by weixsong** [comment]
I will update this mistake later.

**Comment by Harry040** [comment]
thanks for faster reply.

2016-06-30 11:23 GMT+08:00 wei song notifications@github.com:
